### ISSUE TITLE
composer.json issue simplepie/simplepie dev-master

### ISSUE THREAD

**Issue by getafixx** [awjudd/l4-feed-reader#15] opened 2015-07-19 03:16 UTC
Hi there
Trying to use your package here and getting this error

 - awjudd/feed-reader 1.2.0 requires simplepie/simplepie dev-master -> no matching package found.

when doing this

vagrant@homestead:~/1web/1personal_projects/downloaderProject$ composer require awjudd/feed-reader
Using version ^1.2 for awjudd/feed-reader
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for awjudd/feed-reader ^1.2 -> satisfiable by awjudd/feed-reader[1.2.0].
    - awjudd/feed-reader 1.2.0 requires simplepie/simplepie dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
vagrant@homestead:~/1web/1personal_projects/downloaderProject$

My suggesteion is to 

change "simplepie/simplepie": "dev-master" -> "simplepie/simplepie": "1.3.1" and it should fix this issue.

Regards

**Comment by awjudd** [comment] 2015-07-19 03:59
This is a duplicate of #13.  The issue with relying on `'simplepie/simplepie': '1.3.1'` is the fact that there are 66 commits to master which have been made since 1.3.1 was cut.  This includes both enhancements and bug fixes.

Once the following issue is closed (https://github.com/simplepie/simplepie/issues/390), then I will be able to finally move it off of `dev-master`.

**Closed by awjudd** 2015-07-19 03:59 UTC
Labels: duplicate, wontfix

**Comment by getafixx** [comment] 2015-07-19 10:43
thanks

**Comment by ebisbe** [comment] 2016-07-20 10:55
I did a research in order to allow the subdependency to be accepted and still no accept all dev packages.

"prefer-stable" : true,
"minimum-stability": "dev"

http://stackoverflow.com/questions/20068149/how-to-include-dev-masterdev-in-a-subdependency-with-composer
